name: Auto-Merge

on:
  pull_request_review:
    types:
    - submitted

jobs:
  pull_request:
    name: Fetch Pull Request Details
    if: ${{ github.event.review.user.login == 'paketo-bot-reviewer' }}
    runs-on: ubuntu-latest
    steps:
    - name: Fetch
      id: fetch
      env:
        NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
      run: |
        payload="$(
          curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${NUMBER}" \
            --silent \
            --location \
            --header "Authorization: token ${GITHUB_TOKEN}"
        )"

        echo "::set-output name=payload::$(echo "${payload}" | jq -r -c .)"
    outputs:
      payload: ${{ steps.fetch.outputs.payload }}

  merge:
    name: Merge
    needs: pull_request
    #if: ${{ fromJSON(needs.pull_request.outputs.payload).mergeable_state == 'clean' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: State
      env:
        CAN_MERGE: ${{ fromJSON(needs.pull_request.outputs.payload).mergeable_state == 'clean' }}
      run: |
        echo "Can merge? ${CAN_MERGE}"
        exit 1

    - name: Merge
      uses: paketo-buildpacks/github-config/actions/pull-request/merge@automerge
      with:
        user: paketo-bot
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        number: ${{ github.event.pull_request.number }}

  rebase:
    name: Rebase
    needs: pull_request
    if: ${{ fromJSON(needs.pull_request.outputs.payload).mergeable_state == 'behind' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Rebase
      uses: paketo-buildpacks/github-config/actions/pull-request/merge@automerge
      with:
        user: paketo-bot
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
        number: ${{ github.event.pull_request.number }}
